const TermsAndConditions = {
  termsofuseDesc: {
    text1:
      "I.These Terms constitute the entire legal agreement between you and TrueKarma.org, govern your access to and use of the App, and completely replace any prior or contemporaneous agreements between the parties related to your access to or use of the App, whether oral or written. There are no third party beneficiaries to these Terms. The parties are independent contractors, and nothing in these Terms create any agency, partnership, or joint venture. The language in these Terms will be interpreted as to its fair meaning, and not strictly for or against any party. You may not assign any or your rights or obligations under these Terms, whether by operation of law or otherwise, without our prior written consent.",
    text2:
      "II.We may assign our rights and obligations under these Terms in our sole discretion to an affiliate, or in connection with an acquisition, sale or merger. Should any part of these Terms be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions will remain in full force and effect. Our failure to enforce any provision of these Terms will not be deemed a waiver of such provision, nor of the right to enforce such provision. These Terms will be governed by and construed in accordance with the laws of the State of California, excluding its conflicts of law rules and principles.",
    text3:
      "III.Subject to Section 15, any legal action or proceeding arising under these Terms will be brought exclusively in the federal or state courts located in San Francisco County, California, and the parties irrevocably consent to the personal jurisdiction and venue there. We will not be liable for any failure or delayed performance of our obligations that result from any condition beyond our reasonable control, including, but not limited to, governmental action, acts of terrorism, earthquake, fire, flood, acts of God, labor conditions, power failures, Internet disturbances, or acts or omissions of third parties.",
    text4:
      "IV.You agree that we may provide you with notices (including, without limitation those regarding changes to these Terms) by email, regular mail, or postings on the App. By providing us with your email address, you consent to our using the email address to send you any notices required by law in lieu of communication by postal mail."
  },
  privacyPolicy: {
    text1:
      "I.These Terms constitute the entire legal agreement between you and TrueKarma.org, govern your access to and use of the App, and completely replace any prior or contemporaneous agreements between the parties related to your access to or use of the App, whether oral or written. There are no third party beneficiaries to these Terms. The parties are independent contractors, and nothing in these Terms create any agency, partnership, or joint venture. The language in these Terms will be interpreted as to its fair meaning, and not strictly for or against any party. You may not assign any or your rights or obligations under these Terms, whether by operation of law or otherwise, without our prior written consent.",
    text2:
      "II.We may assign our rights and obligations under these Terms in our sole discretion to an affiliate, or in connection with an acquisition, sale or merger. Should any part of these Terms be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions will remain in full force and effect. Our failure to enforce any provision of these Terms will not be deemed a waiver of such provision, nor of the right to enforce such provision. These Terms will be governed by and construed in accordance with the laws of the State of California, excluding its conflicts of law rules and principles.",
    text3:
      "III.Subject to Section 15, any legal action or proceeding arising under these Terms will be brought exclusively in the federal or state courts located in San Francisco County, California, and the parties irrevocably consent to the personal jurisdiction and venue there. We will not be liable for any failure or delayed performance of our obligations that result from any condition beyond our reasonable control, including, but not limited to, governmental action, acts of terrorism, earthquake, fire, flood, acts of God, labor conditions, power failures, Internet disturbances, or acts or omissions of third parties.",
    text4:
      "IV.You agree that we may provide you with notices (including, without limitation those regarding changes to these Terms) by email, regular mail, or postings on the App. By providing us with your email address, you consent to our using the email address to send you any notices required by law in lieu of communication by postal mail."
  }
};

export default TermsAndConditions;
